name: Feature
description: 새로운 기능 추가
title: "[Feat] "
labels: [feature]
assignees: []

body:
  - type: textarea
    attributes:
      label: "설명"
      description: "새로 추가될 기능에 대한 설명을 작성해 주세요."
      
  - type: textarea
    attributes:
      label: "작업 내용"
      description: "새로운 기능 추가를 위해 해야 할 일을 목록화하여 적어주세요."
      placeholder: "- [ ] 작업 내용 << 체크 박스 형태로 목록화해주세요."
